[tool.poetry]
name = "telegram-bot"
version = "0.1.0"
description = ""
authors = ["ivan_kalinov <ikalinov1989@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-telegram-bot = "^22.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
